### ISSUE TITLE
How does this extension handle connections to JIRA?

### ISSUE THREAD

**Issue by tess1o** [Robpol86/Flask-JIRA-Helper#5]
Hello,

Does the extension create a single connection to JIRA and use it for all the requests to JIRA? 
What if connection is expired?  I didn't find answers in your source code.
Will the extension re-connect and create a new session if the session is expired? I didn't find this in the source code.

Thanks!

**Comment by Robpol86** [comment]
I don't remember, I haven't used this in over a year. I used it for a web service with a daily Celery task that used the same instance and I didn't have any connection issues. It Just Worked, but I don't know what our JIRA server config was like. I'm not sure on the answer to your question.
